version: "2.2"
services:
  channel:
    build: "channel_controller/."
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - broker
  broker:
    build: "broker/."
    restart: always
    ports:
      - "5050:5050"
    
